Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2021-05, with the labels that each got.

#702 ETW exporter warnings clean-up, compliance, implementing 2 TODOs
  exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
  exporters/etw/include/opentelemetry/exporters/etw/utils.h
Labels: area:exporter, spec-compliance

#743 Add curl via vcpkg to Windows builds
  tools/setup-buildtools.cmd
Labels: area:exporter, build and test, pr:please-merge

#750 Add --recursive git option to install doc
  INSTALL.md
Labels: pr:please-merge

#749 Disable MSVC warning C4250 for metrics Instrument
  sdk/include/opentelemetry/sdk/metrics/async_instruments.h
  sdk/include/opentelemetry/sdk/metrics/instrument.h
  sdk/include/opentelemetry/sdk/metrics/sync_instruments.h
Labels: pr:please-merge

#786 Add Jaeger exporter to CMake CI build
  .github/workflows/ci.yml
  ci/do_ci.sh
  ci/setup_thrift.sh
  exporters/jaeger/src/thrift_sender.h
  exporters/jaeger/src/udp_transport.h
Labels: build and test
