Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2021-04, with the labels that each got.

#519 Code improvements for ETW exporter
  .github/CODEOWNERS
  CMakeLists.txt
  CMakeSettings.json
  api/include/opentelemetry/common/attribute_value.h
  api/include/opentelemetry/common/key_value_iterable_view.h
  api/include/opentelemetry/trace/span_context_kv_iterable.h
  api/include/opentelemetry/trace/tracer.h
  api/test/nostd/string_view_test.cc
  exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_recordable.h
  exporters/etw/BUILD
  exporters/etw/CMakeLists.txt
  exporters/etw/README.md
  exporters/etw/include/opentelemetry/exporters/etw/.gitignore
  exporters/etw/include/opentelemetry/exporters/etw/etw_data.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_fields.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_traceloggingdynamic.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_tracer_exporter.h
  exporters/etw/include/opentelemetry/exporters/etw/utils.h
  exporters/etw/src/etw_provider_exporter.cc
  exporters/etw/src/etw_tracer_exporter.cc
  exporters/etw/test/etw_perf_test.cc
  exporters/etw/test/etw_provider_test.cc
  exporters/etw/test/etw_tracer_test.cc
  exporters/otlp/CMakeLists.txt
  exporters/otlp/src/recordable.cc
  exporters/zipkin/src/recordable.cc
  sdk/include/opentelemetry/sdk/common/attribute_utils.h
  sdk/include/opentelemetry/sdk/metrics/instrument.h
  tools/setup-buildtools.cmd
Labels: area:exporter

#313 Proposal to add a Google Test Demo Document
  docs/google-test.md
Labels: pr:please-merge

#674 Resolve "Level 4" warnings about unused parameter in interface definitions in span API headers
  api/include/opentelemetry/trace/default_span.h
  api/include/opentelemetry/trace/span_context_kv_iterable.h
Labels: area:api

#679 Attribute value cleanup
  api/docs/Doxyfile
  api/include/opentelemetry/common/attribute_value.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_properties.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_provider.h
  exporters/otlp/src/recordable.cc
  exporters/zipkin/src/recordable.cc
  sdk/include/opentelemetry/sdk/common/attribute_utils.h
Labels: area:api, pr:please-merge

#651 Enable resource detector tests on Windows
  sdk/test/resource/resource_test.cc
Labels: pr:please-merge

#686 Get rid of obsolete core namespace in API
  CHANGELOG.md
  api/include/opentelemetry/common/timestamp.h
  api/include/opentelemetry/logs/logger.h
  api/include/opentelemetry/logs/noop.h
  api/include/opentelemetry/plugin/tracer.h
  api/include/opentelemetry/trace/default_span.h
  api/include/opentelemetry/trace/noop.h
  api/include/opentelemetry/trace/span.h
  api/test/core/timestamp_test.cc
  api/test/logs/logger_test.cc
  api/test/trace/noop_test.cc
  examples/plugin/plugin/tracer.cc
  examples/zpages/zpages_example.cc
  exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_recordable.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_tracer.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_tracer_exporter.h
  exporters/ostream/test/ostream_log_test.cc
  exporters/ostream/test/ostream_span_test.cc
  exporters/otlp/include/opentelemetry/exporters/otlp/recordable.h
  exporters/otlp/src/recordable.cc
  exporters/otlp/test/otlp_exporter_benchmark.cc
  exporters/otlp/test/recordable_test.cc
  exporters/zipkin/include/opentelemetry/exporters/zipkin/recordable.h
  exporters/zipkin/src/recordable.cc
  exporters/zipkin/test/zipkin_recordable_test.cc
  ext/include/opentelemetry/ext/zpages/threadsafe_span_data.h
  ext/test/zpages/threadsafe_span_data_test.cc
  ext/test/zpages/tracez_data_aggregator_test.cc
  sdk/include/opentelemetry/sdk/logs/log_record.h
  sdk/include/opentelemetry/sdk/logs/logger.h
  sdk/include/opentelemetry/sdk/logs/recordable.h
  sdk/include/opentelemetry/sdk/metrics/aggregator/aggregator.h
  sdk/include/opentelemetry/sdk/metrics/aggregator/gauge_aggregator.h
  sdk/include/opentelemetry/sdk/trace/recordable.h
  sdk/include/opentelemetry/sdk/trace/span_data.h
  sdk/src/logs/logger.cc
  sdk/src/trace/span.cc
  sdk/src/trace/span.h
  sdk/test/logs/log_record_test.cc
  sdk/test/trace/span_data_test.cc
  sdk/test/trace/tracer_test.cc
Labels: pr:please-merge

#699 Visual Studio 2019 fixes for API headers
  api/include/opentelemetry/nostd/function_ref.h
  api/include/opentelemetry/nostd/span.h
  api/include/opentelemetry/std/span.h
Labels: pr:please-merge
