Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2022-11, with the labels that each got.

#1736 [Logs SDK] LogProcessor, LogExporter class name
  examples/otlp/README.md
  examples/otlp/grpc_log_main.cc
  examples/otlp/http_log_main.cc
  exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
  exporters/elasticsearch/src/es_log_record_exporter.cc
  exporters/elasticsearch/test/es_log_record_exporter_test.cc
  exporters/ostream/include/opentelemetry/exporters/ostream/log_record_exporter.h
  exporters/ostream/src/log_record_exporter.cc
  exporters/ostream/test/ostream_log_test.cc
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter_factory.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_client.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter_factory.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter_options.h
  exporters/otlp/src/otlp_grpc_log_record_exporter.cc
  exporters/otlp/src/otlp_grpc_log_record_exporter_factory.cc
  exporters/otlp/src/otlp_http_log_record_exporter.cc
  exporters/otlp/src/otlp_http_log_record_exporter_factory.cc
  exporters/otlp/test/otlp_grpc_log_record_exporter_factory_test.cc
  exporters/otlp/test/otlp_grpc_log_record_exporter_test.cc
  exporters/otlp/test/otlp_http_log_record_exporter_factory_test.cc
  exporters/otlp/test/otlp_http_log_record_exporter_test.cc
  sdk/include/opentelemetry/sdk/logs/batch_log_record_processor.h
  sdk/include/opentelemetry/sdk/logs/batch_log_record_processor_factory.h
  sdk/include/opentelemetry/sdk/logs/batch_log_record_processor_options.h
  sdk/include/opentelemetry/sdk/logs/multi_log_record_processor.h
  sdk/include/opentelemetry/sdk/logs/multi_log_record_processor_factory.h
  sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h
  sdk/include/opentelemetry/sdk/logs/simple_log_record_processor_factory.h
  sdk/src/logs/batch_log_record_processor.cc
  sdk/src/logs/batch_log_record_processor_factory.cc
  sdk/src/logs/logger_context.cc
  sdk/src/logs/multi_log_record_processor.cc
  sdk/src/logs/multi_log_record_processor_factory.cc
  sdk/src/logs/simple_log_record_processor.cc
  sdk/src/logs/simple_log_record_processor_factory.cc
  sdk/test/logs/batch_log_record_processor_test.cc
  sdk/test/logs/logger_provider_sdk_test.cc
  sdk/test/logs/simple_log_record_processor_test.cc
Labels: logs

#1779 [BUILD] Upgrade bazel build to use abseil-cpp-20220623.1
  bazel/repository.bzl
Labels: pr:please-merge, build and test

#1796 Fix clang-format in CI
  .github/workflows/ci.yml
Labels: pr:please-merge

#1798 Fix CI build
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
Labels: build and test

#1786 bump to gRPC v1.48.1 for bazel CIs
  bazel/repository.bzl
  ci/do_ci.sh
  exporters/otlp/test/otlp_grpc_exporter_benchmark.cc
  exporters/otlp/test/otlp_http_exporter_test.cc
  exporters/otlp/test/otlp_http_log_record_exporter_test.cc
  exporters/otlp/test/otlp_http_metric_exporter_test.cc
Labels: build and test

#1808 [BUILD] Fix benchmark CI
  .github/workflows/benchmark.yml
Labels: build and test

#1807 [BUILD] Bump abseil-cpp for cmake CI
  ci/do_ci.sh
  ci/install_abseil.sh
  third_party_release
Labels: build and test, size:small

#1811 [BUILD] move client::nosend under test_common
  .github/.codecov.yaml
  CMakeLists.txt
  exporters/otlp/BUILD
  exporters/otlp/CMakeLists.txt
  exporters/otlp/test/otlp_http_exporter_test.cc
  exporters/otlp/test/otlp_http_log_record_exporter_test.cc
  exporters/otlp/test/otlp_http_metric_exporter_test.cc
  ext/include/opentelemetry/ext/http/client/http_client_factory.h
  ext/src/CMakeLists.txt
  test_common/BUILD
  test_common/CMakeLists.txt
  test_common/include/opentelemetry/test_common/ext/http/client/nosend/http_client_nosend.h
  test_common/src/CMakeLists.txt
  test_common/src/http/client/nosend/BUILD
  test_common/src/http/client/nosend/CMakeLists.txt
  test_common/src/http/client/nosend/http_client_factory_nosend.cc
  test_common/src/http/client/nosend/http_client_nosend.cc
Labels: build and test
