Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2023-11, with the labels that each got.

#2255 [SDK] Cardinality limits for metrics streams (Sync Instruments + Delta Temporality)
  sdk/include/opentelemetry/sdk/metrics/state/attributes_hashmap.h
  sdk/include/opentelemetry/sdk/metrics/state/sync_metric_storage.h
  sdk/test/metrics/CMakeLists.txt
  sdk/test/metrics/cardinality_limit_test.cc
Labels: ok-to-merge

#2213 [EXPORTER] Prometheus: Add unit to names, convert to word
  exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
  exporters/prometheus/src/exporter_utils.cc
  exporters/prometheus/test/exporter_utils_test.cc
Labels: area:exporter:prometheus

#2416 [Metrics] Make context optional for histogram instruments in Metrics SDK
  api/include/opentelemetry/metrics/noop.h
  api/include/opentelemetry/metrics/sync_instruments.h
  sdk/include/opentelemetry/sdk/metrics/sync_instruments.h
  sdk/src/metrics/meter.cc
  sdk/src/metrics/sync_instruments.cc
  sdk/test/metrics/sync_instruments_test.cc
Labels: abi:version_2
