Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2023-07, with the labels that each got.

#2214 Add Include what you use
  ci/do_ci.sh
  ci/setup_ci_environment.sh
Labels: area:ci

#2221 [SDK] TracerProvider should own TracerContext, not share it
  CHANGELOG.md
  examples/grpc/tracer_common.h
  examples/http/tracer_common.h
  ext/test/w3c_tracecontext_test/main.cc
  sdk/include/opentelemetry/sdk/logs/logger_context.h
  sdk/include/opentelemetry/sdk/logs/logger_provider.h
  sdk/include/opentelemetry/sdk/logs/logger_provider_factory.h
  sdk/include/opentelemetry/sdk/trace/tracer_provider.h
  sdk/include/opentelemetry/sdk/trace/tracer_provider_factory.h
  sdk/src/logs/logger_provider.cc
  sdk/src/logs/logger_provider_factory.cc
  sdk/src/trace/tracer_provider.cc
  sdk/src/trace/tracer_provider_factory.cc
  sdk/test/logs/logger_provider_sdk_test.cc
  sdk/test/trace/tracer_provider_test.cc
Labels: ok-to-merge

#2205 [API] Remove Meters
  CHANGELOG.md
  CMakeLists.txt
  api/CMakeLists.txt
  api/include/opentelemetry/metrics/meter_provider.h
  api/include/opentelemetry/metrics/noop.h
  ci/do_ci.sh
  exporters/otlp/test/otlp_grpc_log_record_exporter_test.cc
  sdk/include/opentelemetry/sdk/metrics/meter_context.h
  sdk/include/opentelemetry/sdk/metrics/meter_provider.h
  sdk/src/metrics/meter_context.cc
  sdk/src/metrics/meter_provider.cc
  sdk/test/logs/log_record_test.cc
  sdk/test/metrics/meter_provider_sdk_test.cc
Labels: priority:p0, ok-to-merge

#2071 opentelemetry-cpp project CI
  .github/workflows/project_management_comment.yml
  .github/workflows/project_management_issue_open.yml
Labels: do-not-stale, area:ci

#2114 [CI] Upgrade GoogleTest version from 1.12.1 to 1.13.0
  .github/workflows/benchmark.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  CMakeLists.txt
  bazel/repository.bzl
  ci/do_ci.sh
  ci/setup_cmake.sh
  third_party_release
Labels: ok-to-merge

#2236 [Metrics SDK] Add unit to Instrument selection criteria
  CHANGELOG.md
  examples/metrics_simple/metrics_ostream.cc
  examples/prometheus/main.cc
  sdk/include/opentelemetry/sdk/metrics/view/instrument_selector.h
  sdk/include/opentelemetry/sdk/metrics/view/instrument_selector_factory.h
  sdk/include/opentelemetry/sdk/metrics/view/view.h
  sdk/include/opentelemetry/sdk/metrics/view/view_factory.h
  sdk/include/opentelemetry/sdk/metrics/view/view_registry.h
  sdk/src/metrics/view/instrument_selector_factory.cc
  sdk/src/metrics/view/view_factory.cc
  sdk/test/metrics/histogram_aggregation_test.cc
  sdk/test/metrics/histogram_test.cc
  sdk/test/metrics/meter_provider_sdk_test.cc
  sdk/test/metrics/sum_aggregation_test.cc
  sdk/test/metrics/view_registry_test.cc
Labels: ok-to-merge

#2244 Valgrind errors on std::atomic variables
  exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
  exporters/otlp/src/otlp_http_client.cc
  ext/include/opentelemetry/ext/http/client/curl/http_client_curl.h
  ext/include/opentelemetry/ext/http/client/curl/http_operation_curl.h
  ext/include/opentelemetry/ext/zpages/tracez_data_aggregator.h
  ext/test/http/curl_http_test.cc
  sdk/include/opentelemetry/sdk/logs/batch_log_record_processor.h
  sdk/include/opentelemetry/sdk/logs/simple_log_record_processor.h
  sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h
  sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
  sdk/src/logs/batch_log_record_processor.cc
  sdk/src/trace/batch_span_processor.cc
Labels: ok-to-merge
