Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2023-03, with the labels that each got.

#2013 Change SDK version global variable name to lowercase
  buildscripts/pre-commit
  sdk/include/opentelemetry/sdk/version/version.h
  sdk/src/version/version.cc
Labels: ok-to-merge

#2014 Provide version major/minor/patch macros
  CHANGELOG.md
  api/include/opentelemetry/version.h
  api/test/core/BUILD
  api/test/core/CMakeLists.txt
  api/test/core/version_test.cc
Labels: ok-to-merge

#1993 [Metrics SDK] Performance improvement in measurement processing
  sdk/include/opentelemetry/sdk/common/attributemap_hash.h
  sdk/include/opentelemetry/sdk/metrics/state/async_metric_storage.h
  sdk/include/opentelemetry/sdk/metrics/state/attributes_hashmap.h
  sdk/include/opentelemetry/sdk/metrics/state/sync_metric_storage.h
  sdk/include/opentelemetry/sdk/metrics/view/attributes_processor.h
  sdk/src/metrics/state/temporal_metric_storage.cc
  sdk/test/common/attributemap_hash_test.cc
  sdk/test/metrics/BUILD
  sdk/test/metrics/CMakeLists.txt
  sdk/test/metrics/attributes_hashmap_benchmark.cc
  sdk/test/metrics/attributes_hashmap_test.cc
  sdk/test/metrics/measurements_benchmark.cc
Labels: ok-to-merge, size/L

#2021 Fix syntax issue in pre-release script
  buildscripts/pre_release.sh
Labels: ok-to-merge

#2036 Pick old schema url when updating schema url is empty according to specification in Resource::Merge
  CHANGELOG.md
  sdk/include/opentelemetry/sdk/resource/resource.h
  sdk/src/resource/resource.cc
  sdk/test/resource/resource_test.cc
Labels: bug, size/M

#2041 Export factory class of log provider
  api/include/opentelemetry/logs/provider.h
Labels: ok-to-merge

#2040 Checking indices before dereference in string utils
  api/include/opentelemetry/common/string_util.h
Labels: ok-to-merge

#2034 Fix view names in Prometheus example
  examples/prometheus/README.md
  examples/prometheus/main.cc
Labels: size/XS

#2062 Fix default value of `OPENTELEMETRY_INSTALL_default`.
  CHANGELOG.md
  CMakeLists.txt
Labels: ok-to-merge

#2063 Cleanup warnings in ETW exporters
  exporters/etw/include/opentelemetry/exporters/etw/etw_logger.h
  exporters/etw/include/opentelemetry/exporters/etw/etw_tail_sampler.h
Labels: ok-to-merge

#2055 Remove unused 'alerting' section from prometheus.yml in examples
  examples/prometheus/README.md
  examples/prometheus/prometheus.yml
Labels: ok-to-merge

#2000 Add `ForceFlush` for all `LogRecordExporter`s and `SpanExporter`s.
  CHANGELOG.md
  examples/otlp/grpc_log_main.cc
  examples/otlp/grpc_main.cc
  examples/otlp/http_log_main.cc
  examples/otlp/http_main.cc
  exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_record_exporter.h
  exporters/elasticsearch/src/es_log_record_exporter.cc
  exporters/etw/CMakeLists.txt
  exporters/jaeger/BUILD
  exporters/jaeger/CMakeLists.txt
  exporters/jaeger/include/opentelemetry/exporters/jaeger/jaeger_exporter.h
  exporters/jaeger/src/jaeger_exporter.cc
  exporters/ostream/include/opentelemetry/exporters/ostream/log_record_exporter.h
  exporters/ostream/include/opentelemetry/exporters/ostream/span_exporter.h
  exporters/ostream/src/log_record_exporter.cc
  exporters/ostream/src/span_exporter.cc
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_http_log_record_exporter.h
  exporters/otlp/src/otlp_grpc_exporter.cc
  exporters/otlp/src/otlp_grpc_log_record_exporter.cc
  exporters/otlp/src/otlp_http_client.cc
  exporters/otlp/src/otlp_http_exporter.cc
  exporters/otlp/src/otlp_http_log_record_exporter.cc
  exporters/zipkin/include/opentelemetry/exporters/zipkin/zipkin_exporter.h
  exporters/zipkin/src/zipkin_exporter.cc
  sdk/include/opentelemetry/sdk/logs/batch_log_record_processor.h
  sdk/include/opentelemetry/sdk/logs/exporter.h
  sdk/include/opentelemetry/sdk/trace/batch_span_processor.h
  sdk/include/opentelemetry/sdk/trace/exporter.h
  sdk/include/opentelemetry/sdk/trace/simple_processor.h
  sdk/include/opentelemetry/sdk/trace/tracer_context.h
  sdk/src/logs/CMakeLists.txt
  sdk/src/logs/batch_log_record_processor.cc
  sdk/src/logs/exporter.cc
  sdk/src/logs/simple_log_record_processor.cc
  sdk/src/trace/CMakeLists.txt
  sdk/src/trace/batch_span_processor.cc
  sdk/src/trace/exporter.cc
  sdk/src/trace/tracer.cc
  sdk/src/trace/tracer_context.cc
  sdk/test/logs/batch_log_record_processor_test.cc
  sdk/test/logs/simple_log_record_processor_test.cc
  sdk/test/trace/batch_span_processor_test.cc
  sdk/test/trace/simple_processor_test.cc
Labels: size/XL

#2017 Upgraded semantic conventions to 1.19.0
  CHANGELOG.md
  api/include/opentelemetry/trace/semantic_conventions.h
  buildscripts/semantic-convention/generate.sh
  sdk/include/opentelemetry/sdk/resource/semantic_conventions.h
Labels: ok-to-merge

#2064 [Metrics SDK] Implement Forceflush for Periodic Metric Reader
  sdk/include/opentelemetry/sdk/metrics/export/periodic_exporting_metric_reader.h
  sdk/src/metrics/export/periodic_exporting_metric_reader.cc
  sdk/test/metrics/periodic_exporting_metric_reader_test.cc
Labels: ok-to-merge

#2076 Make some targets parallel in CI pipeline (UNIX)
  ci/do_ci.sh
Labels: ok-to-merge
