Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2023-09, with the labels that each got.

#2294 [Metrics SDK] Remove unused member variables from SyncMetricStorage
  sdk/include/opentelemetry/sdk/metrics/state/sync_metric_storage.h
Labels: ok-to-merge

#2222 [API] Deliver ABI breaking changes
  CMakeLists.txt
  api/CMakeLists.txt
  api/include/opentelemetry/version.h
  docs/abi-version-policy.md
Labels: issue:blocking

#2304 [BUILD] Need fine-grained HAVE_CPP_STDLIB
  .github/workflows/ci.yml
  CHANGELOG.md
  CMakeLists.txt
  api/CMakeLists.txt
  api/include/opentelemetry/nostd/shared_ptr.h
  api/include/opentelemetry/nostd/span.h
  api/include/opentelemetry/nostd/string_view.h
  api/include/opentelemetry/nostd/type_traits.h
  api/include/opentelemetry/nostd/unique_ptr.h
  api/include/opentelemetry/nostd/utility.h
  api/include/opentelemetry/nostd/variant.h
  api/include/opentelemetry/std/span.h
  api/test/nostd/span_test.cc
  api/test/nostd/string_view_test.cc
  ci/do_ci.sh
  docs/building-with-stdlib.md
  docs/dependencies.md
  exporters/etw/README.md
  exporters/otlp/test/otlp_grpc_exporter_test.cc
  exporters/otlp/test/otlp_http_exporter_test.cc
  exporters/otlp/test/otlp_http_log_record_exporter_test.cc
  exporters/zipkin/test/zipkin_exporter_test.cc
  ext/test/http/CMakeLists.txt
Labels: pr:please-review

#2224 [API] Add InstrumentationScope attributes in MeterProvider::GetMeter()
  .github/workflows/ci.yml
  CHANGELOG.md
  api/include/opentelemetry/metrics/meter_provider.h
  api/include/opentelemetry/metrics/noop.h
  ci/do_ci.sh
  sdk/include/opentelemetry/sdk/common/attribute_utils.h
  sdk/include/opentelemetry/sdk/metrics/meter_provider.h
  sdk/src/metrics/meter_provider.cc
  sdk/test/metrics/meter_provider_sdk_test.cc
Labels: pr:please-review, abi:version_2
