Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2023-10, with the labels that each got.

#2358 [BUILD] Upgrade libcurl to version 8.4.0
  bazel/repository.bzl
Labels: CVE, pr:please-review

#2263 [BUILD] Support to use different cmake package CONFIG of dependencies.
  CMakeLists.txt
  cmake/patch-imported-config.cmake
  cmake/tools.cmake
Labels: pr:please-review

#2359 [RELEASE] Prepare release 1.12.0
  CHANGELOG.md
  api/include/opentelemetry/version.h
  docs/public/conf.py
  sdk/include/opentelemetry/sdk/version/version.h
  sdk/src/version/version.cc
Labels: pr:please-review

#2371 [API] Add InstrumentationScope attributes in TracerProvider::GetTracer()
  CHANGELOG.md
  api/include/opentelemetry/trace/noop.h
  api/include/opentelemetry/trace/tracer_provider.h
  api/test/singleton/singleton_test.cc
  api/test/trace/provider_test.cc
  sdk/include/opentelemetry/sdk/trace/tracer_provider.h
  sdk/src/trace/tracer_provider.cc
  sdk/test/trace/tracer_provider_test.cc
Labels: abi:version_2

#2380 [API] Add a new AddLink() operation to Span
  CHANGELOG.md
  api/include/opentelemetry/plugin/tracer.h
  api/include/opentelemetry/trace/default_span.h
  api/include/opentelemetry/trace/noop.h
  api/include/opentelemetry/trace/span.h
  api/include/opentelemetry/trace/span_context_kv_iterable.h
  api/test/trace/noop_test.cc
  examples/plugin/plugin/tracer.cc
  sdk/src/trace/span.cc
  sdk/src/trace/span.h
  sdk/test/trace/tracer_test.cc
Labels: abi:version_2
