Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2024-11, with the labels that each got.

#3120 [BUILD] allow building with -DWITH_OTLP_HTTP_COMPRESSION=OFF without zlib
  ext/src/http/client/curl/http_client_curl.cc
Labels: ok-to-merge

#3132 [TEST] Rename w3c_tracecontext_test to w3c_tracecontext_http_test_server
  .github/workflows/ci.yml
  ext/test/CMakeLists.txt
  ext/test/w3c_tracecontext_http_test_server/BUILD
  ext/test/w3c_tracecontext_http_test_server/CMakeLists.txt
  ext/test/w3c_tracecontext_http_test_server/Dockerfile
  ext/test/w3c_tracecontext_http_test_server/README.md
  ext/test/w3c_tracecontext_http_test_server/main.cc
Labels: ok-to-merge

#3139 [SEMANTIC CONVENTIONS] Upgrade to semantic conventions 1.28.0
  api/include/opentelemetry/semconv/incubating/az_attributes.h
  api/include/opentelemetry/semconv/incubating/cloud_attributes.h
  api/include/opentelemetry/semconv/incubating/cloudfoundry_attributes.h
  api/include/opentelemetry/semconv/incubating/container_attributes.h
  api/include/opentelemetry/semconv/incubating/container_metrics.h
  api/include/opentelemetry/semconv/incubating/db_attributes.h
  api/include/opentelemetry/semconv/incubating/db_metrics.h
  api/include/opentelemetry/semconv/incubating/file_attributes.h
  api/include/opentelemetry/semconv/incubating/gen_ai_attributes.h
  api/include/opentelemetry/semconv/incubating/http_attributes.h
  api/include/opentelemetry/semconv/incubating/hw_attributes.h
  api/include/opentelemetry/semconv/incubating/hw_metrics.h
  api/include/opentelemetry/semconv/incubating/k8s_attributes.h
  api/include/opentelemetry/semconv/incubating/k8s_metrics.h
  api/include/opentelemetry/semconv/incubating/log_attributes.h
  api/include/opentelemetry/semconv/incubating/messaging_attributes.h
  api/include/opentelemetry/semconv/incubating/messaging_metrics.h
  api/include/opentelemetry/semconv/incubating/otel_attributes.h
  api/include/opentelemetry/semconv/incubating/process_attributes.h
  api/include/opentelemetry/semconv/incubating/process_metrics.h
  api/include/opentelemetry/semconv/incubating/profile_attributes.h
  api/include/opentelemetry/semconv/incubating/system_metrics.h
  api/include/opentelemetry/semconv/incubating/tls_attributes.h
  api/include/opentelemetry/semconv/schema_url.h
  buildscripts/semantic-convention/generate.sh
Labels: pr:please-review

#3041 [EXPORTER] Allow to share gRPC clients between OTLP exporters
  CHANGELOG.md
  CMakeLists.txt
  api/include/opentelemetry/nostd/internal/absl/README.md
  api/include/opentelemetry/nostd/internal/absl/base/config.h
  api/include/opentelemetry/nostd/internal/absl/base/internal/inline_variable.h
  api/include/opentelemetry/nostd/internal/absl/base/internal/invoke.h
  api/include/opentelemetry/nostd/internal/absl/base/macros.h
  api/include/opentelemetry/nostd/internal/absl/base/options.h
  api/include/opentelemetry/nostd/internal/absl/meta/type_traits.h
  api/include/opentelemetry/nostd/internal/absl/types/bad_variant_access.h
  api/include/opentelemetry/nostd/internal/absl/types/internal/variant.h
  api/include/opentelemetry/nostd/internal/absl/types/variant.h
  api/include/opentelemetry/nostd/internal/absl/utility/utility.h
  api/include/opentelemetry/nostd/variant.h
  cmake/opentelemetry-cpp-config.cmake.in
  cmake/opentelemetry-proto.cmake
  cmake/patch-imported-config.cmake
  examples/grpc/CMakeLists.txt
  exporters/otlp/BUILD
  exporters/otlp/CMakeLists.txt
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_client.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_client_factory.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_exporter_factory.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_log_record_exporter_factory.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter.h
  exporters/otlp/include/opentelemetry/exporters/otlp/otlp_grpc_metric_exporter_factory.h
  exporters/otlp/src/otlp_grpc_client.cc
  exporters/otlp/src/otlp_grpc_client_factory.cc
  exporters/otlp/src/otlp_grpc_exporter.cc
  exporters/otlp/src/otlp_grpc_exporter_factory.cc
  exporters/otlp/src/otlp_grpc_log_record_exporter.cc
  exporters/otlp/src/otlp_grpc_log_record_exporter_factory.cc
  exporters/otlp/src/otlp_grpc_metric_exporter.cc
  exporters/otlp/src/otlp_grpc_metric_exporter_factory.cc
  exporters/otlp/test/otlp_grpc_exporter_factory_test.cc
  exporters/otlp/test/otlp_grpc_log_record_exporter_factory_test.cc
  exporters/otlp/test/otlp_grpc_log_record_exporter_test.cc
  exporters/otlp/test/otlp_grpc_metric_exporter_factory_test.cc
  sdk/src/common/CMakeLists.txt
Labels: ok-to-merge, pr:please-review

#3159 [BUILD] Fix missing dependency on protoc compiler
  cmake/opentelemetry-proto.cmake
Labels: pr:please-review

#3165 [INSTALL] Fix cmake/opentelemetry-cpp-config.cmake.in
  cmake/opentelemetry-cpp-config.cmake.in
Labels: pr:please-review

#3160 [BUILD] Do not set OTELCPP_PROTO_PATH in the CMake cache
  CMakeLists.txt
Labels: pr:please-review

#3168 [RELEASE] Release opentelemetry-cpp 1.18.0
  CHANGELOG.md
  api/include/opentelemetry/version.h
  docs/public/conf.py
  sdk/include/opentelemetry/sdk/version/version.h
  sdk/src/version/version.cc
Labels: pr:please-review

#3140 [Code health] Include what you use cleanup, part 5
  .github/workflows/iwyu.yml
  .iwyu.imp
  api/include/opentelemetry/nostd/variant.h
  api/test/trace/propagation/detail/string_test.cc
  exporters/memory/include/opentelemetry/exporters/memory/in_memory_metric_data.h
  exporters/memory/include/opentelemetry/exporters/memory/in_memory_metric_exporter_factory.h
  exporters/memory/src/in_memory_metric_data.cc
  exporters/memory/src/in_memory_metric_exporter_factory.cc
  exporters/memory/test/in_memory_metric_data_test.cc
  exporters/memory/test/in_memory_metric_exporter_test.cc
  exporters/memory/test/in_memory_span_data_test.cc
  exporters/memory/test/in_memory_span_exporter_test.cc
  exporters/ostream/test/ostream_log_test.cc
  exporters/ostream/test/ostream_metric_test.cc
  exporters/ostream/test/ostream_span_test.cc
  exporters/otlp/src/otlp_file_client.cc
  exporters/otlp/src/otlp_log_recordable.cc
  exporters/otlp/test/otlp_file_client_test.cc
  exporters/otlp/test/otlp_file_exporter_factory_test.cc
  exporters/otlp/test/otlp_file_exporter_test.cc
  exporters/otlp/test/otlp_file_log_record_exporter_factory_test.cc
  exporters/otlp/test/otlp_file_log_record_exporter_test.cc
  exporters/otlp/test/otlp_file_metric_exporter_factory_test.cc
  exporters/otlp/test/otlp_file_metric_exporter_test.cc
  exporters/otlp/test/otlp_http_exporter_factory_test.cc
  exporters/otlp/test/otlp_http_log_record_exporter_factory_test.cc
  exporters/otlp/test/otlp_http_metric_exporter_factory_test.cc
  exporters/otlp/test/otlp_http_metric_exporter_test.cc
  exporters/otlp/test/otlp_log_recordable_test.cc
  exporters/otlp/test/otlp_metrics_serialization_test.cc
  exporters/otlp/test/otlp_recordable_test.cc
  exporters/zipkin/test/zipkin_recordable_test.cc
  ext/test/http/url_parser_test.cc
  ext/test/w3c_tracecontext_http_test_server/main.cc
  sdk/src/metrics/state/metric_collector.cc
  sdk/test/logs/log_record_test.cc
  sdk/test/metrics/histogram_test.cc
  sdk/test/metrics/meter_test.cc
  sdk/test/metrics/multi_metric_storage_test.cc
  sdk/test/metrics/sync_metric_storage_counter_test.cc
  sdk/test/metrics/sync_metric_storage_gauge_test.cc
  sdk/test/metrics/view_registry_test.cc
  sdk/test/trace/sampler_benchmark.cc
Labels: pr:please-review
