Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2024-10, with the labels that each got.

#3076 [RELEASE] Release opentelemetry-cpp 1.17.0
  CHANGELOG.md
  api/include/opentelemetry/version.h
  docs/public/conf.py
  sdk/include/opentelemetry/sdk/version/version.h
  sdk/src/version/version.cc
Labels: pr:please-review

#3086 [API] Jaeger Propagator should not be deprecated
  CHANGELOG.md
  DEPRECATED.md
  api/include/opentelemetry/trace/propagation/jaeger.h
  api/test/trace/propagation/CMakeLists.txt
Labels: pr:please-review

#3104 [EXPORTER] Add config options to prometheus exporter
  exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_options.h
  exporters/prometheus/include/opentelemetry/exporters/prometheus/exporter_utils.h
  exporters/prometheus/src/exporter_options.cc
  exporters/prometheus/src/exporter_utils.cc
  exporters/prometheus/test/exporter_utils_test.cc
Labels: ok-to-merge

#3112 [BUILD] Remove aligned_storage from nostd
  api/include/opentelemetry/nostd/internal/absl/meta/type_traits.h
Labels: pr:waiting-on-cla

#3107 [EXPORTER] Elastic Search exporter follow ECS guidelines
  exporters/elasticsearch/include/opentelemetry/exporters/elasticsearch/es_log_recordable.h
  exporters/elasticsearch/src/es_log_recordable.cc
Labels: ok-to-merge

#3094 [INSTALL] Resolve dependencies in opentelemetry-cpp-config.cmake
  cmake/opentelemetry-cpp-config.cmake.in
Labels: ok-to-merge

#3029 [API] Add synchronous gauge
  api/include/opentelemetry/metrics/meter.h
  api/include/opentelemetry/metrics/noop.h
  api/include/opentelemetry/metrics/sync_instruments.h
  examples/common/metrics_foo_library/foo_library.cc
  examples/common/metrics_foo_library/foo_library.h
  examples/metrics_simple/metrics_ostream.cc
  examples/otlp/file_metric_main.cc
  examples/otlp/grpc_metric_main.cc
  examples/otlp/http_metric_main.cc
  exporters/otlp/src/otlp_metric_utils.cc
  sdk/include/opentelemetry/sdk/metrics/aggregation/default_aggregation.h
  sdk/include/opentelemetry/sdk/metrics/instruments.h
  sdk/include/opentelemetry/sdk/metrics/meter.h
  sdk/include/opentelemetry/sdk/metrics/sync_instruments.h
  sdk/src/metrics/meter.cc
  sdk/src/metrics/state/metric_collector.cc
  sdk/src/metrics/sync_instruments.cc
  sdk/test/metrics/CMakeLists.txt
  sdk/test/metrics/sync_instruments_test.cc
  sdk/test/metrics/sync_metric_storage_gauge_test.cc
Labels: ok-to-merge
