Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2024-07, with the labels that each got.

#2989 [TEST] Fix opentelemetry-collector bind address
  functional/otlp/otel-config-http.yaml
  functional/otlp/otel-config-https.yaml
  functional/otlp/otel-docker-config-http.yaml
  functional/otlp/otel-docker-config-https.yaml
Labels: issue:blocking, pr:please-review

#3002 [CI] Build failures with ABSEIL 20240116 and CMAKE 3.30
  ci/fix-abseil-cpp-issue-1536.patch
  ci/install_abseil.sh
  tools/format.sh
Labels: issue:blocking, pr:please-review

#2995 [CI] Enable bzlmod
  .bazelrc
  MODULE.bazel
  ci/do_ci.ps1
Labels: issue:blocking

#2999 [Metrics SDK] Fix hash calculation for nostd::string
  sdk/include/opentelemetry/sdk/common/attributemap_hash.h
  sdk/test/metrics/attributes_hashmap_test.cc
  sdk/test/metrics/cardinality_limit_test.cc
Labels: ok-to-merge

#3007 [RELEASE] Release opentelemetry-cpp version 1.16.1
  CHANGELOG.md
  api/include/opentelemetry/version.h
  docs/public/conf.py
  sdk/include/opentelemetry/sdk/version/version.h
  sdk/src/version/version.cc
Labels: pr:please-review

#2717 [REMOVAL] Remove build option `WITH_DEPRECATED_SDK_FACTORY`
  .github/workflows/iwyu.yml
  CHANGELOG.md
  CMakeLists.txt
  DEPRECATED.md
  api/CMakeLists.txt
  ci/do_ci.ps1
  ci/do_ci.sh
  examples/logs_simple/main.cc
  examples/metrics_simple/metrics_ostream.cc
  examples/otlp/file_log_main.cc
  examples/otlp/file_main.cc
  examples/otlp/grpc_log_main.cc
  examples/otlp/grpc_main.cc
  examples/otlp/http_log_main.cc
  examples/otlp/http_main.cc
  examples/simple/main.cc
  exporters/otlp/test/otlp_grpc_log_record_exporter_test.cc
  sdk/include/opentelemetry/sdk/logs/event_logger_provider_factory.h
  sdk/include/opentelemetry/sdk/logs/logger_provider_factory.h
  sdk/include/opentelemetry/sdk/metrics/meter_provider_factory.h
  sdk/include/opentelemetry/sdk/trace/tracer_provider_factory.h
  sdk/src/logs/event_logger_provider_factory.cc
  sdk/src/logs/logger_provider_factory.cc
  sdk/src/metrics/meter_provider_factory.cc
  sdk/src/trace/tracer_provider_factory.cc
Labels: removal
