Repository open-telemetry/opentelemetry-cpp, pull requests merged in 2025-06, with the labels that each got.

#3466 [CI] Remove windows 2019
  .github/workflows/ci.yml
  .github/workflows/cmake_install.yml
Labels: pr:please-review

#3476 [REMOVAL] Remove CMake option WITH_REMOVE_METER_PREVIEW
  CMakeLists.txt
Labels: removal

#3486 [CMAKE] Add thirdparty install cmake project and install bash script
  .devcontainer/Dockerfile.dev
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .github/workflows/ci.yml
  .github/workflows/cmake_install.yml
  ci/install_thirdparty.sh
  install/cmake/CMakeLists.txt
  install/cmake/third_party_latest
  install/cmake/third_party_minimum
  install/cmake/third_party_stable
  third_party_release
Labels: ok-to-merge

#3467 [CONFIGURATION] File configuration - trace model
  sdk/include/opentelemetry/sdk/configuration/batch_span_processor_configuration.h
  sdk/include/opentelemetry/sdk/configuration/configuration.h
  sdk/include/opentelemetry/sdk/configuration/console_span_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/otlp_file_span_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/otlp_grpc_span_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/otlp_http_span_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/simple_span_processor_configuration.h
  sdk/include/opentelemetry/sdk/configuration/span_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/span_exporter_configuration_visitor.h
  sdk/include/opentelemetry/sdk/configuration/span_limits_configuration.h
  sdk/include/opentelemetry/sdk/configuration/span_processor_configuration.h
  sdk/include/opentelemetry/sdk/configuration/span_processor_configuration_visitor.h
  sdk/include/opentelemetry/sdk/configuration/tracer_provider_configuration.h
  sdk/include/opentelemetry/sdk/configuration/zipkin_span_exporter_configuration.h
Labels: pr:please-review

#3473 [CONFIGURATION] File configuration - log model
  sdk/include/opentelemetry/sdk/configuration/batch_log_record_processor_configuration.h
  sdk/include/opentelemetry/sdk/configuration/console_log_record_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/log_record_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/log_record_exporter_configuration_visitor.h
  sdk/include/opentelemetry/sdk/configuration/log_record_limits_configuration.h
  sdk/include/opentelemetry/sdk/configuration/log_record_processor_configuration.h
  sdk/include/opentelemetry/sdk/configuration/log_record_processor_configuration_visitor.h
  sdk/include/opentelemetry/sdk/configuration/logger_provider_configuration.h
  sdk/include/opentelemetry/sdk/configuration/otlp_file_log_record_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/otlp_grpc_log_record_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/otlp_http_log_record_exporter_configuration.h
  sdk/include/opentelemetry/sdk/configuration/simple_log_record_processor_configuration.h
Labels: pr:please-review
